---
# tasks file for elk
# vars ไฟล์จะโดนดูดเข้ามาอัตโนมัติทันทีชื่อต้องตาม format yml แท้ๆ ห้ามมีจุด ต้องใช้แบบ key pair indent :
# - name: fdsfsd
#   debug:
#     msg: "{{kibana_password}}"

- name: "git clone project MeetU {{kibana.password}}"
  become: no
  git:
    repo: "https://github.com/wdrdres3qew5ts21/MeetU.git"
    dest: "~/meetu"
    update: yes 


- name: "Start docker-compose Generate SSL & X.509"
  become: no
  docker_compose:
    project_src: "~/meetu"
    files: 
      - create-cert-pem.yml
    state: present

- name: "Teardown all ELK Stack"
  become: no
  docker_compose:
    project_src: "~/meetu"
    files: 
      - docker-compose-elastic-single-full-ssl.yml
    state: absent
    remove_orphans: true 

- name: "Start docker-compose ELK stack ;)"
  become: no
  docker_compose:
    project_src: "~/meetu"
    files: 
      - docker-compose-elastic-single-full-ssl.yml
    state: present
    remove_orphans: true 


- name: Change Kibana Password API
  uri:
    url: "https://localhost:9200/_security/user/kibana/_password?pretty"
    follow_redirects: none
    method: POST
    user: elastic
    password: PleaseChangeMe
    validate_certs: no
    force_basic_auth: yes
    body_format: json
    body: >
      { "password": "{{kibana_password}}" } 
  register: _result
  until: _result.status == 200
  retries: 20 
  delay: 5 

# "{ \"password\": \"{{ kibana_password }}\" }" 
     